///Account

export const HEALTHCHECK_BEGIN = "HEALTHCHECK_BEGIN";
export const BOOSTPROFILE_BEGIN = "BOOSTPROFILE_BEGIN";
export const UPGRADEACCOUNT_BEGIN = "UPGRADEACCOUNT_BEGIN";
export const GETALLUSERS_BEGIN = "GETALLUSERS_BEGIN";
export const SHOWLASTACTIVE_BEGIN = "SHOWLASTACTIVE_BEGIN";
export const PAUSEPROFILE_BEGIN = "PAUSEPROFILE_BEGIN";
export const CREATEPHONEACCOUNT_BEGIN = "CREATEPHONEACCOUNT_BEGIN";
export const FACEBOOKLOGIN_BEGIN = "FACEBOOKLOGIN_BEGIN";
export const GMAILLOGIN_BEGIN = "GMAILLOGIN_BEGIN";
export const GMAILSIGNUP_BEGIN = "GMAILSIGNUP_BEGIN";
export const AUTHORIZEINSTAGRAM_BEGIN = "AUTHORIZEINSTAGRAM_BEGIN";
export const FACEBOOKSIGNUP_BEGIN = "FACEBOOKSIGNUP_BEGIN";
export const GENERATETOKEN_BEGIN = "GENERATETOKEN_BEGIN";
export const ZODIACSIGN_BEGIN = "ZODIACSIGN_BEGIN";
export const CREATEACCOUNTDETAILS_BEGIN = "CREATEACCOUNTDETAILS_BEGIN";
export const CREATEACCOUNTPROFILE_BEGIN = "CREATEACCOUNTPROFILE_BEGIN";
export const UPLOAD_BEGIN = "UPLOAD_BEGIN";
export const GETLISTOFCOUNTRIES_BEGIN = "GETLISTOFCOUNTRIES_BEGIN";
export const UPDATEPROFILE_BEGIN = "UPDATEPROFILE_BEGIN";
export const VERIFYTOKEN_BEGIN = "VERIFYTOKEN_BEGIN";
export const GETSTATESCOUNTRY_BEGIN = "GETSTATESCOUNTRY_BEGIN";
export const GETCITIESSTATE_BEGIN = "GETCITIESSTATE_BEGIN";
export const DASHBOARDBYID_BEGIN = "DASHBOARDBYID_BEGIN";
export const DASHBOARD_BEGIN = "DASHBOARD_BEGIN";
export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGOUT_BEGIN = "LOGOUT_BEGIN";
export const FILTER_BEGIN = "FILTER_BEGIN";

export const HEALTHCHECK_SUCCESS = "HEALTHCHECK_SUCCESS";
export const BOOSTPROFILE_SUCCESS = "BOOSTPROFILE_SUCCESS";
export const UPGRADEACCOUNT_SUCCESS = "UPGRADEACCOUNT_SUCCESS";
export const GETALLUSERS_SUCCESS = "GETALLUSERS_SUCCESS";
export const SHOWLASTACTIVE_SUCCESS = "SHOWLASTACTIVE_SUCCESS";
export const PAUSEPROFILE_SUCCESS = "PAUSEPROFILE_SUCCESS";
export const CREATEPHONEACCOUNT_SUCCESS = "CREATEPHONEACCOUNT_SUCCESS";
export const FACEBOOKLOGIN_SUCCESS = "FACEBOOKLOGIN_SUCCESS";
export const GMAILLOGIN_SUCCESS = "GMAILLOGIN_SUCCESS";
export const GMAILSIGNUP_SUCCESS = "GMAILSIGNUP_SUCCESS";
export const AUTHORIZEINSTAGRAM_SUCCESS = "AUTHORIZEINSTAGRAM_SUCCESS";
export const FACEBOOKSIGNUP_SUCCESS = "FACEBOOKSIGNUP_SUCCESS";
export const GENERATETOKEN_SUCCESS = "GENERATETOKEN_SUCCESS";
export const ZODIACSIGN_SUCCESS = "ZODIACSIGN_SUCCESS";
export const CREATEACCOUNTDETAILS_SUCCESS = "CREATEACCOUNTDETAILS_SUCCESS";
export const CREATEACCOUNTPROFILE_SUCCESS = "CREATEACCOUNTPROFILE_SUCCESS";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const GETLISTOFCOUNTRIES_SUCCESS = "GETLISTOFCOUNTRIES_SUCCESS";
export const UPDATEPROFILE_SUCCESS = "UPDATEPROFILE_SUCCESS";
export const VERIFYTOKEN_SUCCESS = "VERIFYTOKEN_SUCCESS";
export const GETSTATESCOUNTRY_SUCCESS = "GETSTATESCOUNTRY_SUCCESS";
export const GETCITIESSTATE_SUCCESS = "GETCITIESSTATE_SUCCESS";
export const DASHBOARDBYID_SUCCESS = "DASHBOARDBYID_SUCCESS";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const FILTER_SUCCESS = "FILTER_SUCCESS";

export const HEALTHCHECK_FAILURE = "HEALTHCHECK_FAILURE";
export const BOOSTPROFILE_FAILURE = "BOOSTPROFILE_FAILURE";
export const UPGRADEACCOUNT_FAILURE = "UPGRADEACCOUNT_FAILURE";
export const GETALLUSERS_FAILURE = "GETALLUSERS_FAILURE";
export const SHOWLASTACTIVE_FAILURE = "SHOWLASTACTIVE_FAILURE";
export const PAUSEPROFILE_FAILURE = "PAUSEPROFILE_FAILURE";
export const CREATEPHONEACCOUNT_FAILURE = "CREATEPHONEACCOUNT_FAILURE";
export const FACEBOOKLOGIN_FAILURE = "FACEBOOKLOGIN_FAILURE";
export const GMAILLOGIN_FAILURE = "GMAILLOGIN_FAILURE";
export const GMAILSIGNUP_FAILURE = "GMAILSIGNUP_FAILURE";
export const AUTHORIZEINSTAGRAM_FAILURE = "AUTHORIZEINSTAGRAM_FAILURE";
export const FACEBOOKSIGNUP_FAILURE = "FACEBOOKSIGNUP_FAILURE";
export const GENERATETOKEN_FAILURE = "GENERATETOKEN_FAILURE";
export const ZODIACSIGN_FAILURE = "ZODIACSIGN_FAILURE";
export const CREATEACCOUNTDETAILS_FAILURE = "CREATEACCOUNTDETAILS_FAILURE";
export const CREATEACCOUNTPROFILE_FAILURE = "CREATEACCOUNTPROFILE_FAILURE";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";
export const GETLISTOFCOUNTRIES_FAILURE = "GETLISTOFCOUNTRIES_FAILURE";
export const UPDATEPROFILE_FAILURE = "UPDATEPROFILE_FAILURE";
export const VERIFYTOKEN_FAILURE = "VERIFYTOKEN_FAILURE";
export const GETSTATESCOUNTRY_FAILURE = "GETSTATESCOUNTRY_FAILURE";
export const GETCITIESSTATE_FAILURE = "GETCITIESSTATE_FAILURE";
export const DASHBOARDBYID_FAILURE = "DASHBOARDBYID_FAILURE";
export const DASHBOARD_FAILURE = "DASHBOARD_FAILURE";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const FILTER_FAILURE = "FILTER_FAILURE";

////Dating
export const LIKE_BEGIN = "LIKE_BEGIN";
export const FEEDS_BEGIN = "FEEDS_CHECK_BEGIN";
export const SENDMESSAGE_DATING_BEGIN = "SENDMESSAGE_DATING_BEGIN";
export const GETMYCHATTERS_BEGIN = "GETMYCHATTERS_BEGIN";
export const MYMESSAGES_DATING_BEGIN = "MYMESSAGES_DATING_BEGIN";
export const MATCHPROFILE_BEGIN = "MATCHPROFILE_BEGIN";
export const SWIPE_BEGIN = "SWIPE_BEGIN";
export const DISLIKE_BEGIN = "DISLIKE_BEGIN";
export const SEARCHUSER_BEGIN = "SEARCHUSER_BEGIN";
export const GETMYLIKES_BEGIN = "GETMYLIKES_BEGIN";

export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const FEEDS_SUCCESS = "FEEDS_CHECK_SUCCESS";
export const SENDMESSAGE_DATING_SUCCESS = "SENDMESSAGE_DATING_SUCCESS";
export const GETMYCHATTERS_SUCCESS = "GETMYCHATTERS_SUCCESS";
export const MYMESSAGES_DATING_SUCCESS = "MYMESSAGES_DATING_SUCCESS";
export const MATCHPROFILE_SUCCESS = "MATCHPROFILE_SUCCESS";
export const SWIPE_SUCCESS = "SWIPE_SUCCESS";
export const DISLIKE_SUCCESS = "DISLIKE_SUCCESS";
export const SEARCHUSER_SUCCESS = "SEARCHUSER_SUCCESS";
export const GETMYLIKES_SUCCESS = "GETMYLIKES_SUCCESS";

export const LIKE_FAILURE = "LIKE_FAILURE";
export const FEEDS_FAILURE = "FEEDS_CHECK_FAILURE";
export const SENDMESSAGE_DATING_FAILURE = "SENDMESSAGE_DATING_FAILURE";
export const GETMYCHATTERS_FAILURE = "GETMYCHATTERS_FAILURE";
export const MYMESSAGES_DATING_FAILURE = "MYMESSAGES_DATING_FAILURE";
export const MATCHPROFILE_FAILURE = "MATCHPROFILE_FAILURE";
export const SWIPE_FAILURE = "SWIPE_FAILURE";
export const DISLIKE_FAILURE = "DISLIKE_FAILURE";
export const SEARCHUSER_FAILURE = "SEARCHUSER_FAILURE";
export const GETMYLIKES_FAILURE = "GETMYLIKES_FAILURE";

////Gift
export const BUYGIFT_BEGIN = "BUYGIFT_BEGIN";
export const GETALLGIFT_BEGIN = "GETALLGIFT_BEGIN";
export const SELLGIFT_BEGIN = "SELLGIFT_BEGIN";
export const GETALLMYGIFT_BEGIN = "GETALLMYGIFT_BEGIN";
export const GETMYGIFTTOKEN_BEGIN = "GETMYGIFTTOKEN_BEGIN";
export const SENDGIFT_BEGIN = "SENDGIFT_BEGIN";
export const GETMYGIFT_BEGIN = "GETMYGIFT_BEGIN";

export const BUYGIFT_SUCCESS = "BUYGIFT_SUCCESS";
export const GETALLGIFT_SUCCESS = "GETALLGIFT_SUCCESS";
export const SELLGIFT_SUCCESS = "SELLGIFT_SUCCESS";
export const GETALLMYGIFT_SUCCESS = "GETALLMYGIFT_SUCCESS";
export const GETMYGIFTTOKEN_SUCCESS = "GETMYGIFTTOKEN_SUCCESS";
export const SENDGIFT_SUCCESS = "SENDGIFT_SUCCESS";
export const GETMYGIFT_SUCCESS = "GETMYGIFT_SUCCESS";

export const BUYGIFT_FAILURE = "BUYGIFT_FAILURE";
export const GETALLGIFT_FAILURE = "GETALLGIFT_FAILURE";
export const SELLGIFT_FAILURE = "SELLGIFT_FAILURE";
export const GETALLMYGIFT_FAILURE = "GETALLMYGIFT_FAILURE";
export const GETMYGIFTTOKEN_FAILURE = "GETMYGIFTTOKEN_FAILURE";
export const SENDGIFT_FAILURE = "SENDGIFT_FAILURE";
export const GETMYGIFT_FAILURE = "GETMYGIFT_FAILURE";

////Hobby
export const ADDHOBBY_SUCCESS = "ADDHOBBY_SUCCESS";
export const GETHOBBIES_SUCCESS = "GETHOBBIES_SUCCESS";
export const GETHOBBIESBYCATEGORY_SUCCESS = "GETHOBBIESBYCATEGORY_SUCCESS";
export const GETHOBBIESBYUSERID_SUCCESS = "GETHOBBIESBYUSERID_SUCCESS";
export const ADDHOBBYCATEGORY_SUCCESS = "ADDHOBBYCATEGORY_SUCCESS";
export const GETHOBBIESCATEGORY_SUCCESS = "GETHOBBIESCATEGORY_SUCCESS";

export const ADDHOBBY_FAILURE = "ADDHOBBY_FAILURE";
export const GETHOBBIES_FAILURE = "GETHOBBIES_FAILURE";
export const GETHOBBIESBYCATEGORY_FAILURE = "GETHOBBIESBYCATEGORY_FAILURE";
export const GETHOBBIESBYUSERID_FAILURE = "GETHOBBIESBYUSERID_FAILURE";
export const ADDHOBBYCATEGORY_FAILURE = "ADDHOBBYCATEGORY_FAILURE";
export const GETHOBBIESCATEGORY_FAILURE = "GETHOBBIESCATEGORY_FAILURE";

export const ADDHOBBY_BEGIN = "ADDHOBBY_BEGIN";
export const GETHOBBIES_BEGIN = "GETHOBBIES_BEGIN";
export const GETHOBBIESBYCATEGORY_BEGIN = "GETHOBBIESBYCATEGORY_BEGIN";
export const GETHOBBIESBYUSERID_BEGIN = "GETHOBBIESBYUSERID_BEGIN";
export const ADDHOBBYCATEGORY_BEGIN = "ADDHOBBYCATEGORY_BEGIN";
export const GETHOBBIESCATEGORY_BEGIN = "GETHOBBIESCATEGORY_BEGIN";

////Message= "HEALTH_CHECK_SUCCESS";
export const SENDMESSAGE_SUCCESS = "SENDMESSAGE_SUCCESS";
export const MYMESSAGES_SUCESS = "MYMESSAGES_SUCCESS";

export const SENDMESSAGE_FAILURE = "SENDMESSAGE_FAILURE";
export const MYMESSAGES_FAILURE = "MYMESSAGES_FAILURE";

export const SENDMESSAGE_BEGIN = "SENDMESSAGE_BEGIN";
export const MYMESSAGES_BEGIN = "MYMESSAGES_BEGIN";

////Notification= "HEALTH_CHECK_SUCCESS";
export const GETNOTIFICATION_SUCCESS = "GETNOTIFICATION_SUCCESS";
export const VIEWNOTIFICATION_SUCCESS = "VIEWNOTIFICATION_SUCCESS";
export const JOINROOM_SUCCESS = "JOINROOM_SUCCESS";

export const GETNOTIFICATION_FAILURE = "GETNOTIFICATION_FAILURE";
export const VIEWNOTIFICATION_FAILURE = "VIEWNOTIFICATION_FAILURE";
export const JOINROOM_FAILURE = "JOINROOM_FAILURE";

export const GETNOTIFICATION_BEGIN = "GETNOTIFICATION_BEGIN";
export const VIEWNOTIFICATION_BEGIN = "VIEWNOTIFICATION_BEGIN";
export const JOINROOM_BEGIN = "JOINROOM_BEGIN";

////SMS= "HEALTH_CHECK_SUCCESS";
export const QUEUESMS_BEGIN = "QUEUESMS_BEGIN";
export const SENDSMS_BEGIN = "SENDSMS_BEGIN";
export const SENDQUEUEDSMS_BEGIN = "SENDQUEUEDSMS_BEGIN";

export const QUEUESMS_SUCCESS = "QUEUESMS_SUCCESS";
export const SENDSMS_SUCCESS = "SENDSMS_SUCCESS";
export const SENDQUEUEDSMS_SUCCESS = "SENDQUEUEDSMS_SUCCESS";

export const QUEUESMS_FAILURE = "QUEUESMS_FAILURE";
export const SENDSMS_FAILURE = "SENDSMS_FAILURE";
export const SENDQUEUEDSMS_FAILURE = "SENDQUEUEDSMS_FAILURE";

////Special Request= "HEALTH_CHECK_SUCCESS";
export const ADDSPECIALREQUEST_SUCCESS = "ADDSPECIALREQUEST_SUCCESS";
export const SUBMITPROFILE_SUCCESS = "SUBMITPROFILE_SUCCESS";
export const GETALLSPECIALREQUEST_SUCCESS = "GETALLSPECIALREQUEST_SUCCESS";
export const GETPROFILESUBMITTERS_SUCCESS = "GETPROFILESUBMITTERS_SUCCESS";

export const ADDSPECIALREQUEST_FAILURE = "ADDSPECIALREQUEST_FAILURE";
export const SUBMITPROFILE_FAILURE = "SUBMITPROFILE_FAILURE";
export const GETALLSPECIALREQUEST_FAILURE = "GETALLSPECIALREQUEST_FAILURE";
export const GETPROFILESUBMITTERS_FAILURE = "GETPROFILESUBMITTERS_FAILURE";

export const ADDSPECIALREQUEST_BEGIN = "ADDSPECIALREQUEST_BEGIN";
export const SUBMITPROFILE_BEGIN = "SUBMITPROFILE_BEGIN";
export const GETALLSPECIALREQUEST_BEGIN = "GETALLSPECIALREQUEST_BEGIN";
export const GETPROFILESUBMITTERS_BEGIN = "GETPROFILESUBMITTERS_BEGIN";

////Wallet
export const CREATEWALLET_SUCCESS = "CREATEWALLET_SUCCESS";
export const CREDITACCOUNT_SUCCESS = "CREDITACCOUNT_SUCCESS";
export const WALLETINFO_SUCCESS = "WALLETINFO_SUCCESS";
export const WALLETTRANSACTIONS_SUCCESS = "WALLETTRANSACTIONS_SUCCESS";
export const FUNDWALLETWITHCARD_SUCCESS = "FUNDWALLETWITHCARD_SUCCESS";
export const FUNDWALLETWITHBTC_SUCCESS = "FUNDWALLETWITHBTC_SUCCESS";
export const WITHDRAWTOBTCFROMWALLET_SUCCESS =
  "WITHDRAWTOBTCFROMWALLET_SUCCESS";
export const APPROVEBTCTRANSACTION_SUCCESS = "APPROVEBTCTRANSACTION_SUCCESS";

export const CREATEWALLET_BEGIN = "CREATEWALLET_BEGIN";
export const CREDITACCOUNT_BEGIN = "CREDITACCOUNT_BEGIN";
export const WALLETINFO_BEGIN = "WALLETINFO_BEGIN";
export const WALLETTRANSACTIONS_BEGIN = "WALLETTRANSACTIONS_BEGIN";
export const FUNDWALLETWITHCARD_BEGIN = "FUNDWALLETWITHCARD_BEGIN";
export const FUNDWALLETWITHBTC_BEGIN = "FUNDWALLETWITHBTC_BEGIN";
export const WITHDRAWTOBTCFROMWALLET_BEGIN = "WITHDRAWTOBTCFROMWALLET_BEGIN";
export const APPROVEBTCTRANSACTION_BEGIN = "APPROVEBTCTRANSACTION_BEGIN";

export const CREATEWALLET_FAILURE = "CREATEWALLET_FAILURE";
export const CREDITACCOUNT_FAILURE = "CREDITACCOUNT_FAILURE";
export const WALLETINFO_FAILURE = "WALLETINFO_FAILURE";
export const WALLETTRANSACTIONS_FAILURE = "WALLETTRANSACTIONS_FAILURE";
export const FUNDWALLETWITHCARD_FAILURE = "FUNDWALLETWITHCARD_FAILURE";
export const FUNDWALLETWITHBTC_FAILURE = "FUNDWALLETWITHBTC_FAILURE";
export const WITHDRAWTOBTCFROMWALLET_FAILURE =
  "WITHDRAWTOBTCFROMWALLET_FAILURE";
export const APPROVEBTCTRANSACTION_FAILURE = "APPROVEBTCTRANSACTION_FAILURE";


export const CLEAR_REDUX_STATE = "CLEAR_REDUX_STATE";


export const SETGENDER_SUCCESS = "SETGENDER_SUCCESS";
export const SETPHOTO_SUCCESS = "SETPHOTO_SUCCESS";
export const SETLOCATION_SUCCESS = "SETLOCATION_SUCCESS";
export const SETORIGIN_SUCCESS = "SETORIGIN_SUCCESS";
export const SETSEEK_SUCCESS = "SETSEEK_SUCCESS";
export const SETRELIGION_SUCCESS = "SETRELIGION_SUCCESS";
export const SETNAME_SUCCESS = "SETNAME_SUCCESS";
export const SETHOBBIES_SUCCESS = "SETHOBBIES_SUCCESS";
export const SETEMAIL_SUCCESS = "SETEMAIL_SUCCESS";
export const SETAUTH_SUCCESS = "SETAUTH_SUCCESS";
export const SETDOB_SUCCESS = "SETDOB_SUCCESS";
export const SETOCCUPATION_SUCCESS = "SETOCCUPATION_SUCCESS";
export const SETINTERESTIN_SUCCESS = "SETINTERESTIN_SUCCESS";



const types = {
  SETAUTH_SUCCESS,
  SETINTERESTIN_SUCCESS,
  SETOCCUPATION_SUCCESS,
  SETGENDER_SUCCESS,
  CLEAR_REDUX_STATE,
  HEALTHCHECK_BEGIN,
  BOOSTPROFILE_BEGIN,
  UPGRADEACCOUNT_BEGIN,
  GETALLUSERS_BEGIN,
  SHOWLASTACTIVE_BEGIN,
  PAUSEPROFILE_BEGIN,
  CREATEPHONEACCOUNT_BEGIN,
  FACEBOOKLOGIN_BEGIN,
  GMAILLOGIN_BEGIN,
  GMAILSIGNUP_BEGIN,
  AUTHORIZEINSTAGRAM_BEGIN,
  FACEBOOKSIGNUP_BEGIN,
  GENERATETOKEN_BEGIN,
  ZODIACSIGN_BEGIN,
  CREATEACCOUNTDETAILS_BEGIN,
  CREATEACCOUNTPROFILE_BEGIN,
  UPLOAD_BEGIN,
  GETLISTOFCOUNTRIES_BEGIN,
  UPDATEPROFILE_BEGIN,
  VERIFYTOKEN_BEGIN,
  GETSTATESCOUNTRY_BEGIN,
  GETCITIESSTATE_BEGIN,
  DASHBOARDBYID_BEGIN,
  DASHBOARD_BEGIN,
  LOGIN_BEGIN,
  LOGOUT_BEGIN,
  FILTER_BEGIN,
  HEALTHCHECK_SUCCESS,
  BOOSTPROFILE_SUCCESS,
  UPGRADEACCOUNT_SUCCESS,
  GETALLUSERS_SUCCESS,
  SHOWLASTACTIVE_SUCCESS,
  PAUSEPROFILE_SUCCESS,
  CREATEPHONEACCOUNT_SUCCESS,
  FACEBOOKLOGIN_SUCCESS,
  GMAILLOGIN_SUCCESS,
  GMAILSIGNUP_SUCCESS,
  AUTHORIZEINSTAGRAM_SUCCESS,
  FACEBOOKSIGNUP_SUCCESS,
  GENERATETOKEN_SUCCESS,
  ZODIACSIGN_SUCCESS,
  CREATEACCOUNTDETAILS_SUCCESS,
  CREATEACCOUNTPROFILE_SUCCESS,
  UPLOAD_SUCCESS,
  GETLISTOFCOUNTRIES_SUCCESS,
  UPDATEPROFILE_SUCCESS,
  VERIFYTOKEN_SUCCESS,
  GETSTATESCOUNTRY_SUCCESS,
  GETCITIESSTATE_SUCCESS,
  DASHBOARDBYID_SUCCESS,
  DASHBOARD_SUCCESS,
  LOGIN_SUCCESS,
  LOGOUT_SUCCESS,
  FILTER_SUCCESS,
  HEALTHCHECK_FAILURE,
  BOOSTPROFILE_FAILURE,
  UPGRADEACCOUNT_FAILURE,
  GETALLUSERS_FAILURE,
  SHOWLASTACTIVE_FAILURE,
  PAUSEPROFILE_FAILURE,
  CREATEPHONEACCOUNT_FAILURE,
  FACEBOOKLOGIN_FAILURE,
  GMAILLOGIN_FAILURE,
  GMAILSIGNUP_FAILURE,
  AUTHORIZEINSTAGRAM_FAILURE,
  FACEBOOKSIGNUP_FAILURE,
  GENERATETOKEN_FAILURE,
  ZODIACSIGN_FAILURE,
  CREATEACCOUNTDETAILS_FAILURE,
  CREATEACCOUNTPROFILE_FAILURE,
  UPLOAD_FAILURE,
  GETLISTOFCOUNTRIES_FAILURE,
  UPDATEPROFILE_FAILURE,
  VERIFYTOKEN_FAILURE,
  GETSTATESCOUNTRY_FAILURE,
  GETCITIESSTATE_FAILURE,
  DASHBOARDBYID_FAILURE,
  DASHBOARD_FAILURE,
  LOGIN_FAILURE,
  LOGOUT_FAILURE,
  FILTER_FAILURE,
  LIKE_BEGIN,
  FEEDS_BEGIN,
  SENDMESSAGE_DATING_BEGIN,
  GETMYCHATTERS_BEGIN,
  MYMESSAGES_DATING_BEGIN,
  MATCHPROFILE_BEGIN,
  SWIPE_BEGIN,
  DISLIKE_BEGIN,
  SEARCHUSER_BEGIN,
  GETMYLIKES_BEGIN,
  LIKE_SUCCESS,
  FEEDS_SUCCESS,
  SENDMESSAGE_DATING_SUCCESS,
  GETMYCHATTERS_SUCCESS,
  MYMESSAGES_DATING_SUCCESS,
  MATCHPROFILE_SUCCESS,
  SWIPE_SUCCESS,
  DISLIKE_SUCCESS,
  SEARCHUSER_SUCCESS,
  GETMYLIKES_SUCCESS,
  LIKE_FAILURE,
  FEEDS_FAILURE,
  SENDMESSAGE_DATING_FAILURE,
  GETMYCHATTERS_FAILURE,
  MYMESSAGES_DATING_FAILURE,
  MATCHPROFILE_FAILURE,
  SWIPE_FAILURE,
  DISLIKE_FAILURE,
  SEARCHUSER_FAILURE,
  GETMYLIKES_FAILURE,
  BUYGIFT_BEGIN,
  GETALLGIFT_BEGIN,
  SELLGIFT_BEGIN,
  GETALLMYGIFT_BEGIN,
  GETMYGIFTTOKEN_BEGIN,
  SENDGIFT_BEGIN,
  GETMYGIFT_BEGIN,
  BUYGIFT_SUCCESS,
  GETALLGIFT_SUCCESS,
  SELLGIFT_SUCCESS,
  GETALLMYGIFT_SUCCESS,
  GETMYGIFTTOKEN_SUCCESS,
  SENDGIFT_SUCCESS,
  GETMYGIFT_SUCCESS,
  BUYGIFT_FAILURE,
  GETALLGIFT_FAILURE,
  SELLGIFT_FAILURE,
  GETALLMYGIFT_FAILURE,
  GETMYGIFTTOKEN_FAILURE,
  SENDGIFT_FAILURE,
  GETMYGIFT_FAILURE,
  ADDHOBBY_SUCCESS,
  GETHOBBIES_SUCCESS,
  GETHOBBIESBYCATEGORY_SUCCESS,
  GETHOBBIESBYUSERID_SUCCESS,
  ADDHOBBYCATEGORY_SUCCESS,
  GETHOBBIESCATEGORY_SUCCESS,
  ADDHOBBY_FAILURE,
  GETHOBBIES_FAILURE,
  GETHOBBIESBYCATEGORY_FAILURE,
  GETHOBBIESBYUSERID_FAILURE,
  ADDHOBBYCATEGORY_FAILURE,
  GETHOBBIESCATEGORY_FAILURE,
  ADDHOBBY_BEGIN,
  GETHOBBIES_BEGIN,
  GETHOBBIESBYCATEGORY_BEGIN,
  GETHOBBIESBYUSERID_BEGIN,
  ADDHOBBYCATEGORY_BEGIN,
  GETHOBBIESCATEGORY_BEGIN,

  ////Message,
  SENDMESSAGE_SUCCESS,
  MYMESSAGES_SUCESS,
  SENDMESSAGE_FAILURE,
  MYMESSAGES_FAILURE,
  SENDMESSAGE_BEGIN,
  MYMESSAGES_BEGIN,

  ////Notification,
  GETNOTIFICATION_SUCCESS,
  VIEWNOTIFICATION_SUCCESS,
  JOINROOM_SUCCESS,
  GETNOTIFICATION_FAILURE,
  VIEWNOTIFICATION_FAILURE,
  JOINROOM_FAILURE,
  GETNOTIFICATION_BEGIN,
  VIEWNOTIFICATION_BEGIN,
  JOINROOM_BEGIN,

  ////SMS,
  QUEUESMS_BEGIN,
  SENDSMS_BEGIN,
  SENDQUEUEDSMS_BEGIN,
  QUEUESMS_SUCCESS,
  SENDSMS_SUCCESS,
  SENDQUEUEDSMS_SUCCESS,
  QUEUESMS_FAILURE,
  SENDSMS_FAILURE,
  SENDQUEUEDSMS_FAILURE,

  ////Special Request,
  ADDSPECIALREQUEST_SUCCESS,
  SUBMITPROFILE_SUCCESS,
  GETALLSPECIALREQUEST_SUCCESS,
  GETPROFILESUBMITTERS_SUCCESS,
  ADDSPECIALREQUEST_FAILURE,
  SUBMITPROFILE_FAILURE,
  GETALLSPECIALREQUEST_FAILURE,
  GETPROFILESUBMITTERS_FAILURE,
  ADDSPECIALREQUEST_BEGIN,
  SUBMITPROFILE_BEGIN,
  GETALLSPECIALREQUEST_BEGIN,
  GETPROFILESUBMITTERS_BEGIN,

  ////Wallet
  CREATEWALLET_SUCCESS,
  CREDITACCOUNT_SUCCESS,
  WALLETINFO_SUCCESS,
  WALLETTRANSACTIONS_SUCCESS,
  FUNDWALLETWITHCARD_SUCCESS,
  FUNDWALLETWITHBTC_SUCCESS,
  WITHDRAWTOBTCFROMWALLET_SUCCESS,
  APPROVEBTCTRANSACTION_SUCCESS,

  CREATEWALLET_BEGIN,
  CREDITACCOUNT_BEGIN,
  WALLETINFO_BEGIN,
  WALLETTRANSACTIONS_BEGIN,
  FUNDWALLETWITHCARD_BEGIN,
  FUNDWALLETWITHBTC_BEGIN,
  WITHDRAWTOBTCFROMWALLET_BEGIN,
  APPROVEBTCTRANSACTION_BEGIN,

  CREATEWALLET_FAILURE,
  CREDITACCOUNT_FAILURE,
  WALLETINFO_FAILURE,
  WALLETTRANSACTIONS_FAILURE,
  FUNDWALLETWITHCARD_FAILURE,
  FUNDWALLETWITHBTC_FAILURE,
  WITHDRAWTOBTCFROMWALLET_FAILURE,
  APPROVEBTCTRANSACTION_FAILURE,



   SETPHOTO_SUCCESS ,
 SETLOCATION_SUCCESS ,
 SETORIGIN_SUCCESS ,
 SETSEEK_SUCCESS ,
 SETRELIGION_SUCCESS ,
 SETNAME_SUCCESS ,
 SETHOBBIES_SUCCESS ,
 SETEMAIL_SUCCESS ,
 SETDOB_SUCCESS ,
};
export default types;
